version: '2'

services:
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: master
        ports:
          - 3306:3306
        volumes:
          - mysqldata1:/var/lib/mysql
    mailhog:
        image: mailhog/mailhog:v1.0.0
        ports:
          - 8025:8025
          - 1025:1025
    rabbitmq:
        image: rabbitmq:3.7-management
        build: rabbitmq/
        ports:
          - 15672:15672
          - 5672:5672
volumes:
  mysqldata1:
    driver: local
